//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.01.04 at 09:43:54 AM CET 
//


package org.ceskaexpedice.fedoramodel;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.qbizm.kramerius.imp.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.qbizm.kramerius.imp.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DigitalObject }
     * 
     */
    public DigitalObject createDigitalObject() {
        return new DigitalObject();
    }

    /**
     * Create an instance of {@link DigitalObjectType }
     * 
     */
    public DigitalObjectType createDigitalObjectType() {
        return new DigitalObjectType();
    }

    /**
     * Create an instance of {@link ObjectPropertiesType }
     * 
     */
    public ObjectPropertiesType createObjectPropertiesType() {
        return new ObjectPropertiesType();
    }

    /**
     * Create an instance of {@link DatastreamType }
     * 
     */
    public DatastreamType createDatastreamType() {
        return new DatastreamType();
    }

    /**
     * Create an instance of {@link DatastreamVersionType }
     * 
     */
    public DatastreamVersionType createDatastreamVersionType() {
        return new DatastreamVersionType();
    }

    /**
     * Create an instance of {@link ContentDigestType }
     * 
     */
    public ContentDigestType createContentDigestType() {
        return new ContentDigestType();
    }

    /**
     * Create an instance of {@link XmlContentType }
     * 
     */
    public XmlContentType createXmlContentType() {
        return new XmlContentType();
    }

    /**
     * Create an instance of {@link ContentLocationType }
     * 
     */
    public ContentLocationType createContentLocationType() {
        return new ContentLocationType();
    }

    /**
     * Create an instance of {@link PropertyType }
     * 
     */
    public PropertyType createPropertyType() {
        return new PropertyType();
    }

    /**
     * Create an instance of {@link ExtpropertyType }
     * 
     */
    public ExtpropertyType createExtpropertyType() {
        return new ExtpropertyType();
    }

}
