//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.01.04 at 09:43:54 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "info:fedora/fedora-system:def/foxml#", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.ceskaexpedice.model;
